[project]
name = "ghostguns"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "geopandas>=1.0.1",
    "ipykernel>=6.30.1",
    "matplotlib>=3.9.4",
    "pandas>=2.3.2",
    "plotly>=6.3.0",
]
